### ISSUE TITLE
Preprocessing step fails with no report on CSV with missing header field

### ISSUE THREAD

**Issue by meganforbes** [collectionspace/cspace-batch-import#47]
As noted, upload file with one missing header (but data in the column), click on start preprocessing step, and the step fails with no report.

**Comment by kspurgin** [comment]
@meganforbes -- can you upload this test CSV?

**Comment by meganforbes** [comment]
[CSV Import Test 2a no field name.csv](https://github.com/collectionspace/cspace-batch-import/files/6312851/CSV.Import.Test.2a.no.field.name.csv)
